services:
  #smtp:
  #  container_name: moneytalks-smtp
  
  db:
    container_name: moneytalks-db
    image: postgres:15-alpine
    volumes:
      - ../data/postgres:/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=moneytalks
    ports:
      - 5432:5432
    