import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import { getServerSession } from 'next-auth'
import SessionProvider from '@/components/SessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Moneytalks',
  description: 'Generated by create next app',
}

export const fetchCache = 'default-no-store'

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()
  return (
      <html lang="en">
          <body className={inter.className}>
              <SessionProvider session={session}>
                  <Header />
                  {children}
              </SessionProvider>
          </body>
      </html>
  )
}
